name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      accountKey: ${{ secrets.accountKey }}
      accountEndpoint: ${{ secrets.accountEndpoint }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up
